### PR TITLE
Distribute README

### PR DESCRIPTION
**Pull request by szepeviktor**
```
$ git archive HEAD | tar --list --exclude="src" --exclude="src/*"
LICENSE
README.md
composer.json
data/
data/country-to-currency.php
data/iso-currencies.php
data/numeric-to-currency.php
```

### CODE REVIEW

**Comment by solodkiy** [comment]
Why not?

**Comment by szepeviktor** [comment]
From this comment
https://github.com/nicebooks-com/isbn/pull/4#issuecomment-1732412525

**Comment by BenMorel** [comment]
Actually I think that both README and CHANGELOG should be part of the exported archive.

@szepeviktor Could you please update your PR accordingly?

**Comment by szepeviktor** [comment]
@BenMorel Done 🍏

**Comment by BenMorel** [comment]
That was fast! :racehorse: Thank you, @szepeviktor.

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
