### PR TITLE
Keep releases lean

### PR DESCRIPTION
**Pull request by raphaelstolt**
Keep unnecessary files out of releases/dists. If you want to ship the license file remove it's export-ignore.

### CODE REVIEW

**Comment by BenMorel** [comment]
👍 Please don't export-ignore the license file, and I'll merge it!

**Comment by BenMorel** [comment]
And please add export-ignore for import-currencies.php as mentioned in #10!

**Comment by raphaelstolt** [comment]
IMO it shouldn't be export ignored, so that a library user can import / update currencies independently from the maintainer; given that this data changes frequently.

**Comment by BenMorel** [comment]
Looks good, thanks!

**Pull request merged**
