### PR TITLE
Goodbye manual Composer file editing

### PR DESCRIPTION
**Pull request by raphaelstolt**
Let Composer modify the composer.json and resolve the library it's latest version.

### CODE REVIEW

**Comment by BenMorel** [comment]
I'd like to keep the existing JSON and wording, but feel free to just add right after the JSON:

---

Or just run:

    composer require brick/money

---

**Comment by raphaelstolt** [comment]
I get your point regarding the wording change, but keeping the JSON is obsolete for two reasons:

- adding any dependencies manually is a smell
- the version in it has to be updated with very tagged release you make

**Comment by BenMorel** [comment]
I don't know about that, I always prefer to keep an eye on my composer.json version constraints manually. Updating the version in the README is not a big deal!

Please keep it as it is for now, but you can add the `composer require` first:

> Just run:
> composer require brick/money
> or manually define the following requirement in your `composer.json` file:
> ...

**Comment by BenMorel** [comment]
👍

**Pull request merged**
